- project:
    templates:
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
