- project:
    templates:
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
