.. -*- rst -*-

API Versions
============

List api versions
~~~~~~~~~~~~~~~~~

.. rest_method:: GET /

Lists information of Venus API versions.

Response codes
--------------

.. rest_status_code:: success ../status.yaml

   - 1

.. rest_status_code:: error ../status.yaml

   - -1

Response
--------

**Example List Api Versions: JSON response**


.. literalinclude:: ./samples/versions-response.json
   :language: javascript
