.. -*- rst -*-

API versions
============

List All Api Versions
~~~~~~~~~~~~~~~~~~~~~

.. rest_method:: GET /

Lists information for all Venus API versions.

Response codes
--------------

.. rest_status_code:: success ../parameters.yaml

   - 0

.. rest_status_code:: error ../parameters.yaml

   - -1

Response
--------

**Example List Api Versions: JSON request**


.. literalinclude:: ./samples/versions-response.json
   :language: javascript
